[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@selfxyz/contracts/=node_modules/@selfxyz/contracts/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@aave/core-v3/=node_modules/@aave/core-v3/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
